=== tdwg/cd/standard/schemas/json/2.0/latimer-core-vocabulary.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema#",
    "$id": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/latimer-core-vocabulary.schema.json",
    "title": "Latimer Core Vocabulary JSON Schema",  
    "description": "JSON Schema (compliant with the JSON Schema Specification Draft 2020-12) for the Latimer Core Vocabulary Schemas",
    "type": "object",
    "properties": {
        "$schema": {"type": "string"},
        "$id": {"type": "string"},
        "title": {"type": "string"},
        "description": {"type": "string"},
        "type": {"type": "string"},
        "properties": {"$ref": "#/$defs/properties_type"}
    },
    "$defs": {
        "items_type": {
            "type": "object",
            "properties": {
                "$ref": {"type": "string"},
                "description": {"type": "string"},
                "type": {"type": "string"}
            }
        },
        "properties_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "description": {"type": "string"},
                    "name": {"type": "string"},
                    "type": {"type": "string"},
                    "items": {"$ref": "#/$defs/items_type"},
                    "minItems": {"type": "integer"},
                    "uniqueItems": {"type": "boolean"}
                },
                "required": [
                    "name",
                    "description",
                    "type"
                ]
            }
        }
    }
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/person.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/latimer-core-schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/person.json",
  "title": "Person",
  "description": "A person (alive or dead). This concept should map to the Schema.org Person class (https://schema.org/Person), and the prov:Person class (http://www.w3.org/ns/prov#Person) in the PROV ontology. In the latter, it is a subclass of prov:Agent, which through which it can map to the RDA recommendations on attribution (http://dx.doi.org/10.15497/RDA00029). The definition is appropriated from the Schema.org class.",
  "type": "object",
  "properties": [
	{
			"name": "additionalName",
			"description": "An additional name for a Person, can be used for a middle name.",
			"type": "string"
		},
		{
			"name": "familyName",
			"description": "Family name. In the U.S., the last name of a Person.",
			"type": "string"
		},
		{
			"name": "fullName",
			"description": "Preferred form of personal name for display as a string.",
			"type": "string"
		},
		{
			"name": "givenName",
			"description": "Given name. In the U.S., the first name of a Person.",
			"type": "string"
		},
		{
			"name": "hasAddress",
			"description": "This property refers to one or more related instances of the Address class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/address.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasContactDetail",
			"description": "This property refers to one or more related instances of the ContactDetail class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/contact-detail.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasMeasurementOrFact",
			"description": "This property refers to one or more related instances of the MeasurementOrFact class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/measurement-or-fact.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		}
	]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/reference.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/latimer-core-vocabulary.schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/reference.json",
  "title": "Reference",
  "description": "A reference to external resources and information related to the collection description. In the Collection Description standard, this class can be used to store references to publications, policies, datasets and other online resources such as websites, related to classes within the standard.",
  "type": "object",
  "properties": [
	{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "referenceDetails",
			"description": "Detailed information about the resource being referenced.",
			"type": "string"
		},
		{
			"name": "referenceText",
			"description": "A short title for the reference.",
			"type": "string"
		},
		{
			"name": "referenceType",
			"description": "The type of resource being referenced.",
			"type": "string"
		},
		{
			"name": "resourceURI",
			"description": "A preferably resolvable URI to uniquely identify a concept.",
			"type": "string"
		}
	]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/geographic-origin.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json/json-schemas/1.0/latimer-core-schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json/vocabulary-schemas/1.0/geographic-origin.json",
  "title": "Geographic Origin",
  "description": "The geographic location from which objects associated with the ObjectGroup were collected.",
  "type": "object",
  "properties": [
	{
			"name": "continent",
			"description": "The name of the continent in which the Location occurs.",
			"type": "string"
		},
		{
			"name": "country",
			"description": "The name of the country or major administrative unit in which the Location occurs.",
			"type": "string"
		},
		{
			"name": "countryCode",
			"description": "The standard code for the country in which the Location occurs.",
			"type": "string"
		},
		{
			"name": "county",
			"description": "The full, unabbreviated name of the next smaller administrative region than stateProvince (county, shire, department, etc.) in which the Location occurs.",
			"type": "string"
		},
		{
			"name": "ecoRegion",
			"description": "High level biogeographic region of the location.",
			"type": "string"
		},
		{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasMeasurementOrFact",
			"description": "This property refers to one or more related instances of the MeasurementOrFact class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/measurement-or-fact.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "island",
			"description": "The name of the island on or near which the Location occurs.",
			"type": "string"
		},
		{
			"name": "islandGroup",
			"description": "The name of the island group in which the Location occurs.",
			"type": "string"
		},
		{
			"name": "locality",
			"description": "The specific description of the place. Less specific geographic information can be provided in other geographic terms (higherGeography, continent, country, stateProvince, county, municipality, waterBody, island, islandGroup). This term may contain information modified from the original to correct perceived errors or standardize the description.",
			"type": "string"
		},
		{
			"name": "municipality",
			"description": "The full, unabbreviated name of the next smaller administrative region than county (city, municipality, etc.) in which the Location occurs. Do not use this term for a nearby named place that does not contain the actual location.",
			"type": "string"
		},
		{
			"name": "region",
			"description": "The name of a spatial region or named place of any size within an individual or multiple administrative areas.",
			"type": "string"
		},
		{
			"name": "salinityType",
			"description": "A set of terms to indicate the water environment of aquatic collections.",
			"type": "string"
		},
		{
			"name": "stateProvince",
			"description": "The name of the next smaller administrative region than country (state, province, canton, department, region, etc.) in which the Location occurs.",
			"type": "string"
		},
		{
			"name": "waterBody",
			"description": "The name of the water body in which the Location occurs.",
			"type": "string"
		},
		{
			"name": "waterBodyType",
			"description": "A term that indicates the aquatic order of a waterbody.",
			"type": "string"
		}
	]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/event.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json/json-schemas/1.0/latimer-core-schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json/vocabulary-schemas/1.0/event.json",
  "title": "Event",
  "description": "An action that occurs at some location during some time. Derived from dwc Class event (http://rs.tdwg.org/dwc/terms/version/Event-2018-09-06). This class has been defined under the ltc namespace because it only has a subset of the properties of DwC:Event. All ltc:Event properties are borrowed from and reference the dwc namespace. Examples of an Event include: A specimen collection process. A camera trap image capture. A marine trawl.",
  "type": "object",
  "properties": [
	{
			"name": "eventName",
			"description": "The name commonly used to identify or refer to the event.",
			"type": "string"
		},
		{
			"name": "habitat",
			"description": "A category or description of the habitat in which the Event occurred.",
			"type": "string"
		},
		{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasMeasurementOrFact",
			"description": "This property refers to one or more related instances of the MeasurementOrFact class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/measurement-or-fact.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasPersonRole",
			"description": "This property refers to one or more related instances of the PersonRole class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/person-role.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasTemporalCoverage",
			"description": "This property refers to one or more related instances of the TemporalCoverage class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/temporal-coverage.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "samplingProtocol",
			"description": "The name of, reference to, or description of the method or protocol used during an Event",
			"type": "string"
		},
		{
			"name": "verbatimEventDate",
			"description": "The verbatim original representation of the date and time information for an Event.",
			"type": "string"
		}
	]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/temporal-coverage.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/latimer-core-vocabulary.schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/temporal-coverage.json",
  "title": "Temporal Coverage",
  "description": "A record of a time range represented by the collection's establishment or change over time. This term is separate from the living or geologic periods represented by the objects in the collection. This class can be used to reflect temporal coverage of the collection within various contexts (defined by the temporalCoverageType property). Examples might include the time range in which objects within the collection were collected or the time period over which the collection was assembled.  It should not be used to document the time range within which the objects in the collection were alive, and if the time period you are trying to describe is better described by the `CollectionHistory`, `GeologicalContext` or `ChronometricAge` classes, or period property of the `ObjectGroup` class, then those classes or properties should be used instead. For example, the period property of the `ObjectGroup` class and/or `GeologicalContext` class should be used to record named time periods. `TemporalCoverage` is a repeatable class, but when present as a property of `Event` or `CollectionStatusHistory`, multiple occurences should be avoided and repeated occurences of the parent class should be used instead.",
  "type": "object",
  "properties": [
	{
			"name": "hasMeasurementOrFact",
			"description": "This property refers to one or more related instances of the MeasurementOrFact class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/measurement-or-fact.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "temporalCoverageEndDate",
			"description": "End date of the time range of the collection.",
			"type": "string"
		},
		{
			"name": "temporalCoverageStartDate",
			"description": "Start date of the time range of the collection.",
			"type": "string"
		},
		{
			"name": "temporalCoverageType",
			"description": "The type or context of the time range associated with the collection's establishment. Separate from the living or geologic periods represented by the objects in the collection.",
			"type": "string"
		}
	]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/chronometric-age.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/chronometric-age-schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/chronometric-age.json",
  "title": "Chronometric Age",
  "description": "The age of a specimen or related materials that is generated from a dating assay. This is a categorical term (class) to organize the other chronometric age properties and does not ever have values.",
  "type": "object",
  "properties": [
	{
			"name": "chronometricAgeProtocol",
			"description": "A description of or reference to the methods used to determine the ChronometricAge.",
			"type": "string"
		},
		{
			"name": "chronometricAgeRemarks",
			"description": "Notes or comments about the ChronometricAge.",
			"type": "string"
		},
		{
			"name": "chronometricAgeUncertaintyInYears",
			"description": "The temporal uncertainty of the earliestChronometricAge and latestChronometicAge in years.",
			"type": "number"
		},
		{
			"name": "earliestChronometricAge",
			"description": "The maximum/earliest/oldest possible age of a specimen as determined by a dating method.",
			"type": "number"
		},
		{
			"name": "earliestChronometricAgeReferenceSystem",
			"description": "The reference system associated with the earliestChronometricAge.",
			"type": "string"
		},
		{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasMeasurementOrFact",
			"description": "This property refers to one or more related instances of the MeasurementOrFact class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/measurement-or-fact.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "latestChronometricAge",
			"description": "The minimum/latest/youngest possible age of a specimen as determined by a dating method.",
			"type": "number"
		},
		{
			"name": "latestChronometricAgeReferenceSystem",
			"description": "The reference system associated with the latestChronometricAge.",
			"type": "string"
		},
		{
			"name": "verbatimChronometricAge",
			"description": "The verbatim age for a specimen, whether reported by a dating assay, associated references, or legacy information.",
			"type": "string"
		}
	]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/taxon.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/latimer-core-schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/taxon.json",
  "title": "Taxon",
  "description": "A group of organisms (sensu http://purl.obolibrary.org/obo/OBI_0100026) considered by taxonomists to form a homogeneous unit.",
  "type": "object",
  "properties": [
	{
			"name": "genus",
			"description": "The full scientific name of the genus in which the taxon is classified.",
			"type": "string"
		},
		{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasMeasurementOrFact",
			"description": "This property refers to one or more related instances of the MeasurementOrFact class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/measurement-or-fact.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "kingdom",
			"description": "The full scientific name of the kingdom in which the taxon is classified.",
			"type": "string"
		},
		{
			"name": "scientificName",
			"description": "The full scientific name, with authorship and date information if known. When forming part of an Identification, this should be the name in lowest level taxonomic rank that can be determined. This term should not contain identification qualifications, which should instead be supplied in the IdentificationQualifier term.",
			"type": "string"
		},
		{
			"name": "taxonRank",
			"description": "The taxonomic rank of the most specific name in the scientificName.",
			"type": "string"
		}
	]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/geological-context.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/latimer-core-vocabulary.schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/geological-context.json",
  "title": "Geological Context",
  "description": "Geological information, such as stratigraphy, that qualifies a region or place.",
  "type": "object",
  "properties": [
	{
			"name": "bed",
			"description": "The full name of the lithostratigraphic bed from which the cataloged item was collected.",
			"type": "string"
		},
		{
			"name": "earliestAgeOrLowestStage",
			"description": "The full name of the earliest possible geochronologic age or lowest chronostratigraphic stage attributable to the stratigraphic horizon from which the cataloged item was collected",
			"type": "string"
		},
		{
			"name": "earliestEonOrLowestEonothem",
			"description": "The full name of the earliest possible geochronologic eon or lowest chrono-stratigraphic eonothem or the informal name (Precambrian) attributable to the stratigraphic horizon from which the cataloged item was collected.",
			"type": "string"
		},
		{
			"name": "earliestEpochOrLowestSeries",
			"description": "The full name of the earliest possible geochronologic epoch or lowest chronostratigraphic series attributable to the stratigraphic horizon from which the cataloged item was collected.",
			"type": "string"
		},
		{
			"name": "earliestEraOrLowestErathem",
			"description": "The full name of the earliest possible geochronologic era or lowest chronostratigraphic erathem attributable to the stratigraphic horizon from which the cataloged item was collected.",
			"type": "string"
		},
		{
			"name": "earliestPeriodOrLowestSystem",
			"description": "The full name of the earliest possible geochronologic period or lowest chronostratigraphic system attributable to the stratigraphic horizon from which the cataloged item was collected.",
			"type": "string"
		},
		{
			"name": "formation",
			"description": "The full name of the lithostratigraphic formation from which the cataloged item was collected.",
			"type": "string"
		},
		{
			"name": "group",
			"description": "The full name of the lithostratigraphic group from which the cataloged item was collected.",
			"type": "string"
		},
		{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasMeasurementOrFact",
			"description": "This property refers to one or more related instances of the MeasurementOrFact class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/measurement-or-fact.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "latestAgeOrHighestStage",
			"description": "The full name of the latest possible geochronologic age or highest chronostratigraphic stage attributable to the stratigraphic horizon from which the cataloged item was collected.",
			"type": "string"
		},
		{
			"name": "latestEonOrHighestEonothem",
			"description": "The full name of the latest possible geochronologic eon or highest chrono-stratigraphic eonothem or the informal name (Precambrian) attributable to the stratigraphic horizon from which the cataloged item was collected.",
			"type": "string"
		},
		{
			"name": "latestEpochOrHighestSeries",
			"description": "The full name of the latest possible geochronologic epoch or highest chronostratigraphic series attributable to the stratigraphic horizon from which the cataloged item was collected.",
			"type": "string"
		},
		{
			"name": "latestEraOrHighestErathem",
			"description": "The full name of the latest possible geochronologic era or highest chronostratigraphic erathem attributable to the stratigraphic horizon from which the cataloged item was collected.",
			"type": "string"
		},
		{
			"name": "latestPeriodOrHighestSystem",
			"description": "The full name of the latest possible geochronologic period or highest chronostratigraphic system attributable to the stratigraphic horizon from which the cataloged item was collected.",
			"type": "string"
		},
		{
			"name": "member",
			"description": "The full name of the lithostratigraphic member from which the cataloged item was collected.",
			"type": "string"
		}
	]
}
