=== tdwg/cd/standard/json-schema/event.json
{
    "$schema": "https://json-schema.org/draft-04/schema#",
    "$id": "https://raw.githubusercontent.com/tdwg/cd/master/standard/json-schema/event.json",
    "title": "Event",
    "description": "An action that occurs at some location during some time.",
    "type": "object",
    "properties":
    {
        "verbatimEventDate":
        {
            "description": "The verbatim original representation of the date and time information for an Event.",
            "type": "string"
        },
        "habitat":
        {
            "description": "A category or description of the habitat in which the Event occurred.",
            "type": "string"
        },
        "samplingProtocol":
        {
            "description": "The name of, reference to, or description of the method or protocol used to gather objects in the collection.",
            "type": "string"
        },
        "personRole":
        {
            "description": "One or more Person Roles relating to the Event",
            "type": "array",
            "items":
            {
                "$ref": "https://raw.githubusercontent.com/tdwg/cd/master/standard/json-schema/person-role.json"
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "identifier":
        {
            "description": "One or more Identifiers relating to the Event",
            "type": "array",
            "items":
            {
                "$ref": "https://raw.githubusercontent.com/tdwg/cd/master/standard/json-schema/identifier.json"
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "reference":
        {
            "description": "One or more References relating to the Event",
            "type": "array",
            "items":
            {
                "$ref": "https://raw.githubusercontent.com/tdwg/cd/master/standard/json-schema/reference.json"
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "temporalCoverage":
        {
            "description": "One or more TemporalCoverages relating to the Event",
            "type": "array",
            "items":
            {
                "$ref": "https://raw.githubusercontent.com/tdwg/cd/master/standard/json-schema/temporal-coverage.json"
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "measurementOrFact":
        {
            "description": "One or more Measurement Or Facts relating to the Event",
            "type": "array",
            "items":
            {
                "$ref": "https://raw.githubusercontent.com/tdwg/cd/master/standard/json-schema/measurement-or-fact.json"
            },
            "minItems": 1,
            "uniqueItems": true
        }
    }
}

=== tdwg/cd/examples/class-level json examples/event-example.json
{
    "verbatimEventDate": "1755-1756",
    "habitat": "temperate rainforest",
    "personRole":
    [
        {
            "role": "Collector",
            "startedAtTime": "1755-09-01",
            "person":
            [
                {
                    "fullName": "Anne Monson",
                    "familyName": "Monson",
                    "givenName": "Anne",
                    "identifier":
                    [
                        {
                            "identifierType": "URI",
                            "identifierSource": "https://www.wikidata.org/wiki/",
                            "identifier": "Q15994645"
                        }
                    ]
                }
            ]
        },
        {
            "role": "Navigator",
            "startedAtTime": "1755-09-01",
            "person":
            [
                {
                    "fullName": "Sidney Smith",
                    "familyName": "Smith",
                    "givenName": "Sidney"
                }
            ]
        }
    ],
    "measurementOrFact":
    [
        {
            "measurementType": "Object Count",
            "measurementValue": 500,
            "measurementAccuracy": "Estimate",
            "measurementDerivation": "Reported"
        }
    ]
}
