=== tdwg/cd/standard/json-schema/geological-context.json
{
  "$schema": "https://json-schema.org/draft-04/schema",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/geological-context.json",
  "title": "Geological Context",
  "description": "Geological information, such as stratigraphy, that qualifies a region or place.",
  "type": "object",
  "properties": {
    "bed": {
      "description": "The full name of the lithostratigraphic bed from which the cataloged item was collected.",
      "type": "string"
    },
    "earliestAgeOrLowestStage": {
      "description": "The full name of the earliest possible geochronologic age or lowest chronostratigraphic stage attributable to the stratigraphic horizon from which the cataloged item was collected",
      "type": "string"
    },
    "earliestEonOrLowestEonothem": {
      "description": "The full name of the earliest possible geochronologic eon or lowest chrono-stratigraphic eonothem or the informal name (Precambrian) attributable to the stratigraphic horizon from which the cataloged item was collected.",
      "type": "string"
    },
    "earliestEpochOrLowestSeries": {
      "description": "The full name of the earliest possible geochronologic epoch or lowest chronostratigraphic series attributable to the stratigraphic horizon from which the cataloged item was collected.",
      "type": "string"
    },
    "earliestEraOrLowestErathem": {
      "description": "The full name of the earliest possible geochronologic era or lowest chronostratigraphic erathem attributable to the stratigraphic horizon from which the cataloged item was collected.",
      "type": "string"
    },
    "earliestPeriodOrLowestSystem": {
      "description": "The full name of the earliest possible geochronologic period or lowest chronostratigraphic system attributable to the stratigraphic horizon from which the cataloged item was collected.",
      "type": "string"
    },
    "formation": {
      "description": "The full name of the lithostratigraphic formation from which the cataloged item was collected.",
      "type": "string"
    },
    "group": {
      "description": "The full name of the lithostratigraphic group from which the cataloged item was collected.",
      "type": "string"
    },
    "hasIdentifier": {
      "description": "This property refers to one or more related instances of the Identifier class.",
      "type": "array",
      "items": {
        "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/identifier.json"
      },
      "minItems": 0,
      "uniqueItems": true
    },
    "hasMeasurementOrFact": {
      "description": "This property refers to one or more related instances of the MeasurementOrFact class.",
      "type": "array",
      "items": {
        "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/measurement-or-fact.json"
      },
      "minItems": 0,
      "uniqueItems": true
    },
    "hasReference": {
      "description": "This property refers to one or more related instances of the Reference class.",
      "type": "array",
      "items": {
        "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/reference.json"
      },
      "minItems": 0,
      "uniqueItems": true
    },
    "latestAgeOrHighestStage": {
      "description": "The full name of the latest possible geochronologic age or highest chronostratigraphic stage attributable to the stratigraphic horizon from which the cataloged item was collected.",
      "type": "string"
    },
    "latestEonOrHighestEonothem": {
      "description": "The full name of the latest possible geochronologic eon or highest chrono-stratigraphic eonothem or the informal name (Precambrian) attributable to the stratigraphic horizon from which the cataloged item was collected.",
      "type": "string"
    },
    "latestEpochOrHighestSeries": {
      "description": "The full name of the latest possible geochronologic epoch or highest chronostratigraphic series attributable to the stratigraphic horizon from which the cataloged item was collected.",
      "type": "string"
    },
    "latestEraOrHighestErathem": {
      "description": "The full name of the latest possible geochronologic era or highest chronostratigraphic erathem attributable to the stratigraphic horizon from which the cataloged item was collected.",
      "type": "string"
    },
    "latestPeriodOrHighestSystem": {
      "description": "The full name of the latest possible geochronologic period or highest chronostratigraphic system attributable to the stratigraphic horizon from which the cataloged item was collected.",
      "type": "string"
    },
    "member": {
      "description": "The full name of the lithostratigraphic member from which the cataloged item was collected.",
      "type": "string"
    }
  }
}

=== tdwg/cd/examples/class-level json examples/geological-context-example.json
{
    "latestAgeOrHighestStage": "Thanetian",
    "earliestAgeOrLowestStage": "Albian",
    "latestEpochOrHighestSeries": "Paleocene",
    "earliestEpochOrLowestSeries": "Lower Cretaceous",
    "latestPeriodOrHighestSystem": "Paleogene",
    "earliestPeriodOrLowestSystem": "Cretaceous",
    "latestEraOrHighestErathem": "Mesozoic",
    "earliestEraOrLowestErathem": "Cenozoic"
}
