=== tdwg/cd/standard/json-schema/measurement-or-fact.json
{
  "$schema": "https://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/master/standard/json-schema/measurement-or-fact.json",
  "title": "Measurement or Fact",
  "description": "A measurement of or fact about a class within the standard, or a relationship between the ObjectGroup and an associated class.",
  "type": "object",
  "properties": {
    "measurementType": {
      "description": "The nature of the measurement, fact, characteristic, or assertion.",
      "type": "string"
    },
    "measurementValue": {
      "description": "The numeric value of the quantitative measurement being made about the collection.",
      "type": "number"
    },
    "measurementAccuracy": {
      "description": "The description of the potential error associated with the measurementValue applied to the collection.",
      "type": "string"
    },
    "measurementUnit": {
      "description": "The units associated with the measurementValue.",
      "type": "string"
    },
    "measurementMethod": {
      "description": "A description of or reference to (publication, URI) the method or protocol used to determine the measurement, fact, characteristic, or assertion.",
      "type": "string"
    },
    "measurementRemarks": {
      "description": "Comments or notes accompanying the MeasurementOrFact.",
      "type": "string"
    },
    "measurementDerivation": {
      "description": "An indicator as to whether the measurement, fact, characteristic, or assertion being applied to the collection was derived from reported figures or aggregated/calculated from underlying data.",
      "type": "string"
    },
    "measurementFactText": {
      "description": "The value of the qualitative fact, characteristic, or assertion being made about the collection.",
      "type": "string"
    },
    "hasIdentifier": {
      "description": "This property refers to one or more related instances of the Identifier class.",
      "type": "array",
      "items": {
        "$ref": "https://raw.githubusercontent.com/tdwg/cd/master/standard/json-schema/identifier.json"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "hasReference": {
      "description": "This property refers to one or more related instances of the Reference class.",
      "type": "array",
      "items": {
        "$ref": "https://raw.githubusercontent.com/tdwg/cd/master/standard/json-schema/reference.json"
      },
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "anyOf": [
    {"required" : ["measurementFactText"]},
    {"required" : ["measurementValue"]}

  ]
}

=== tdwg/cd/examples/class-level json examples/measurement-or-fact-example.json
{
    "measurementType": "MIDS-0 Object Count",
    "measurementValue": 500,
    "measurementAccuracy": "Estimate",
    "measurementMethod": "DiSSCo MIDS level",
    "measurementDerivation": "Reported",
    "hasReference":
    [
        {
            "referenceType": "Measurement methodology",
            "resourceURI": "https://doi.org/10.5281/zenodo.3465285",
            "referenceDetails": "Saarenmaa, Hannu, Agosti, Donat, Dillen, Mathias, Egloff, Willi, Gagnier, Pierre-Yves, Groom, Quentin, Hardisty, Alex, & Raes, Niels. (2019). Open access implementation guidelines for DiSSCo. Deliverable D6.5 (pp. 1â€“35).",
            "referenceText": "Open access implementation guidelines for DiSSCo. Deliverable D6.5",
            "hasIdentifier":
            [
                {
                    "identifierType": "DOI",
                    "identifier": "10.5281/zenodo.3465285"
                }
            ]
        }
    ]
}
