=== tdwg/cd/standard/schemas/json/2.0/term-schemas/resource-relationship-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema#",
    "type": "object",
    "properties": {
        "$schema": {"type": "string"},
        "$id": {"type": "string"},
        "title": {"type": "string"},
        "description": {"type": "string"},
        "type": {"type": "string"},
        "properties": {"$ref": "#/$defs/properties_type"},
        "required": {"$ref": "#/$defs/required_type"}
    },
    "$defs": {
        "items_type": {
            "type": "object",
            "properties": {
                "$ref": {"type": "string"},
                "description": {"type": "string"},
                "type": {"type": "string"}
            }
        },
        "properties_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "description": {"type": "string"},
                    "type": {"type": "string"},
                    "items": {"$ref": "#/$defs/items_type"},
                    "minItems": {"type": "integer"},
                    "uniqueItems": {"type": "boolean"}
                },
                "required": [
                    "name",
                    "description",
                    "type"
                ]
            }
        },
        "required_type": {
            "type": "array",
            "minItems": 0,
            "items": {"type": "string"}
        }
    }
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/resource-relationship.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/latimer-core-schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/resource-relationship.json",
  "title": "Resource Relationship",
  "description": "A relationship between an instance of a class in the collection description standard to another instance of the same class, or an instance of a different class in the standard. In the context of this standard, the resources are the collections of objects represented by the ObjectGroup. This class can be used to define different semantic and hierarchical relationships between ObjectGroups.",
  "type": "object",
  "properties": [
	{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "relatedResourceID",
			"description": "An identifier for a related resource (the object, rather than the subject of the relationship).",
			"type": "string"
		},
		{
			"name": "relatedResourceName",
			"description": "A short textual name for the related resource.",
			"type": "string"
		},
		{
			"name": "relationshipAccordingTo",
			"description": "The source (person, organization, publication, reference) establishing the relationship between the two resources.",
			"type": "array",
			"items": {
		  "description": "The source (person, organization, publication, reference) establishing the relationship between the two resources.",
		  "type": "string"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "relationshipEstablishedDate",
			"description": "The date-time on which the relationship between the two resources was established.",
			"type": "string"
		},
		{
			"name": "relationshipOfResource",
			"description": "The relationship of the subject (identified by resourceID) to the object (identified by relatedResourceID).",
			"type": "string"
		},
		{
			"name": "relationshipRemarks",
			"description": "Comments or notes about the relationship between the two resources.",
			"type": "string"
		},
		{
			"name": "resourceID",
			"description": "An identifier for the resource that is the subject of the relationship.",
			"type": "string"
		},
		{
			"name": "resourceRelationshipID",
			"description": "An identifier for an instance of relationship between one resource (the subject) and another (relatedResource, the object).",
			"type": "string"
    }
	],
  "required": [
    "relationshipOfResource",
    "resourceID"
  ]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/organisational-unit.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json/json-schemas/1.0/latimer-core-schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json/vocabulary-schemas/1.0/organisational-unit.json",
  "title": "Organisational Unit",
  "description": "A unit within an organisational hierarchy which may be at, above or below the institutional level. This class can represent any level of organisational unit, incorporating institutions (e.g. a museum), higher units (e.g. a university to which a museum belongs) and more detailed structures (e.g the departments and divisions within a museum). It can be used to arrange these different units at different levels into a hierarchical structure. This class combines aspects of both class org:Organization (https://www.w3.org/TR/2014/REC-vocab-org-20140116/#org:Organization) and class org:OrganizationalUnit (https://www.w3.org/TR/2014/REC-vocab-org-20140116/#org:OrganizationalUnit) from the W3C Organization Ontology ORG (https://www.w3.org/TR/2014/REC-vocab-org-20140116/#overview-of-ontology). Recommended best practice is to associate a unique, persistent organisational identifier (PID) with each created organisational unit. This will allow an unambiguous and continual identification of the unit, as well as the creation of organisational hierarchies. Existing providers of PIDs for organisations are, e.g. https://grid.ac/ and https://ror.org/. The provision of organisational PIDs might be extended to intra-organisational units in the future. Properties of Class: Identifier can be used to add identifier information for organisational units.",
  "type": "object",
  "properties": [
	{
			"name": "hasAddress",
			"description": "This property refers to one or more related instances of the Address class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/address.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasContactDetail",
			"description": "This property refers to one or more related instances of the ContactDetail class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/contact-detail.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasMeasurementOrFact",
			"description": "This property refers to one or more related instances of the MeasurementOrFact class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/measurement-or-fact.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasOrganisationalUnit",
			"description": "This property refers to one or more related instances of the OrganisationalUnit class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/organisational-unit.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasPersonRole",
			"description": "This property refers to one or more related instances of the PersonRole class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/person-role.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "organisationalUnitName",
			"description": "An official name of the organisational unit in the local language.",
			"type": "string"
		},
		{
			"name": "organisationalUnitType",
			"description": "The type or level of organisational unit within a hierarchy responsible for the management of the collection being described.",
			"type": "string"
    }
	],
  "required": [
    "organisationalUnitName",
    "organisationalUnitType"
  ]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/scheme-term.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/latimer-core-schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/scheme-term.json",
  "title": "Scheme Term",
  "description": "A Latimer Core term used by the CollectionDescriptionScheme and the rules relating to its application. This class can be used to define which of the terms (classes and/or properties) within the standard (e.g. GeographicOrigin, Taxon, preservationMethod) are expected to be used within the scheme, and specify whether they're mandatory and/or repeatable. This information can be used by software and queries to validate the data and understand the rules by which metrics can be reported against the specified term.",
  "type": "object",
  "properties": [
	{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "isMandatoryTerm",
			"description": "A flag to designate whether it is mandatory or optional for all ObjectGroups in the CollectionDescriptionScheme to include or be linked to valid data for the class or property defined in the termName property.",
			"type": "boolean"
		},
		{
			"name": "isRepeatableTerm",
			"description": "A flag to designate whether multiple instances of the Latimer Core class or property defined in the termName property may be attached to a single ObjectGroup.",
			"type": "boolean"
		},
		{
			"name": "termName",
			"description": "The name of a class or property within the Latimer Core standard that is included in the CollectionDescriptionScheme.",
			"type": "string"
    }
	],
  "required": [
    "isMandatoryTerm",
    "isRepeatableTerm",
    "termName"
  ]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/person-role.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json/json-schemas/1.0/latimer-core-schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json/vocabulary-schemas/1.0/person-role.json",
  "title": "Person Role",
  "description": "A qualified association between a Person or OrganisationalUnit and an entity such as an ObjectGroup or MeasurementOrFact that enables the relationship to be contextualised with a specific role and time period. This class is aligned with the prov:qualifiedAttribution property (http://www.w3.org/ns/prov#qualifiedAttribution). It should be used instead of the Activity and PersonActivity classes to link a Person or OrganisationalUnit to an entity in situations where an activity is not know or is irrelevant, for example for describing a person's role within an organisation.",
  "type": "object",
  "properties": [
	{
			"name": "endedAtTime",
			"description": "The date or time when a Person stopped fulfilling the role specified in the role property.",
			"type": "string"
		},
		{
			"name": "hasAddress",
			"description": "This property refers to one or more related instances of the Address class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/address.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasContactDetail",
			"description": "This property refers to one or more related instances of the ContactDetail class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/contact-detail.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasMeasurementOrFact",
			"description": "This property refers to one or more related instances of the MeasurementOrFact class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/measurement-or-fact.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasPerson",
			"description": "This property refers to one or more related instances of the Person class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/person.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasTemporalCoverage",
			"description": "This property refers to one or more related instances of the TemporalCoverage class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/temporal-coverage.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "role",
			"description": "A role played by a Person in the context of an entity such as an ObjectGroup, OrganisationalUnit or RecordLevel.",
			"type": "string"
		},
		{
			"name": "startedAtTime",
			"description": "The date or time when a Person started fulfilling the role specified in the role property.",
			"type": "string"
    }
	],
  "required": [
    "role"
  ]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/identifier.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/latimer-core-vocabulary.schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/identifier.json",
  "title": "Identifier",
  "description": "A numeric, textual value, or reference such as an IRI, that can be used to uniquely identify the object to which it is attached. Use this class to document stable identifiers that describe the collections and associated entities being represented in the collection description. For example, person identifiers, taxon identifiers, institution identifiers, organisational unit identifiers, gazetteer identifiers. Identifiers represented by this class may be globally unique, or unique within a given context.",
  "type": "object",
  "properties": [
	{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "identifierSource",
			"description": "The source or creator of the identifier.",
			"type": "string"
		},
		{
			"name": "identifierType",
			"description": "The type and format of the value in the identifier field.",
			"type": "string"
		},
		{
			"name": "identifierValue",
			"description": "An unambiguous reference to the resource within a given context.",
			"type": "string"
    }
	],
  "required": [
    "identifierType",
    "identifierValue"
  ]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/collection-status-history.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json/json-schemas/1.0/latimer-core-schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json/vocabulary-schemas/1.0/collection-status-history.json",
  "title": "Collection Status History",
  "description": "A record of current and past statuses of the object group and the reason for status changes. Use this class to record the history of and reason for changes in the status of the described collection. Types of status described by this class may, for example, include ownership, management, accessibility or accrual policy over time. Dates reflecting the start and end of the status described by this class should be recorded using an instance of TemporalCoverage. If temporalCoverageEndDate is empty, the status can be inferred to be the current status of the collection.",
  "type": "object",
  "properties": [
	{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasMeasurementOrFact",
			"description": "This property refers to one or more related instances of the MeasurementOrFact class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/measurement-or-fact.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasTemporalCoverage",
			"description": "This property refers to one or more related instances of the TemporalCoverage class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/temporal-coverage.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "status",
			"description": "The development status of the collection during a specified period.",
			"type": "string"
		},
		{
			"name": "statusChangeReason",
			"description": "An explanation of why the collection transitioned to the value set in the status property.",
			"type": "string"
		},
		{
			"name": "statusType",
			"description": "A top-level classification of the different categories of status that can be applied to the collection.",
			"type": "string"
    }
	],
  "required": [
    "status",
    "statusType"
  ]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/collection-description-scheme.json
{
"$schema": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/latimer-core-vocabulary.schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json/vocabulary-schemas/1.0/collection-description-scheme.json",
  "title": "Collection Description Scheme",
  "description": "A grouping of multiple ObjectGroups for a particular use case, purpose or implementation. Where the same objects within the same collection might be described by more than one ObjectGroup for different purposes (for examples, a 'Darwin Fossil Mammals' collection description might overlap with a 'Offsite Palaeontology' collection description), this class can be used to distinguish between them and avoid double-counting of metrics in queries against the data.",
  "type": "object",
  "properties": [
	{
			"name": "basisOfScheme",
			"description": "A summary of the basis or purpose for the CollectionDescriptionScheme.",
			"type": "string"
		},
		{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasObjectGroup",
			"description": "This property refers to one or more related instances of the ObjectGroup class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/object-group.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasSchemeMeasurementOrFact",
			"description": "This property refers to one or more related instances of the SchemeMeasurementOrFact class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/scheme-measurement-or-fact.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasSchemeTerm",
			"description": "This property refers to one or more related instances of the SchemeTerm class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/scheme-term.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "isDistinctObjects",
			"description": "A flag to designate whether a physical object may be described by more than one ObjectGroup within the CollectionDescriptionScheme.",
			"type": "boolean"
		},
		{
			"name": "schemeName",
			"description": "A short descriptive name given to the CollectionDescriptionScheme.",
			"type": "string"
    }
	],
  "required": [
    "isDistinctObjects",
    "schemeName"
  ]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/address.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json/json-schemas/1.0/latimer-core-schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json/vocabulary-schemas/1.0/address.json",
  "title": "Address",
  "description": "A physical postal address for an organisational unit or person.",
  "type": "object",
  "properties": [
		{
			"name": "addressCountry",
			"description": "The country. For example, USA. You can also provide the two-letter ISO 3166-1 alpha-2 country code.",
			"type": "string"
		},
		{
			"name": "addressLocality",
			"description": "The locality in which the street address is, and which is in the region. For example, Mountain View.",
			"type": "string"
		},
		{
			"name": "addressRegion",
			"description": "The region in which the locality is, and which is in the country. For example, California or another appropriate first-level Administrative division.",
			"type": "string"
		},
		{
			"name": "addressType",
			"description": "A person or organization can have different addresses, for different purposes. For example, a postal address, a loan address, an address for visits and so on. This property is used to specify the kind of address.",
			"type": "string"
		},
		{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/standard/json-schema/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "postOfficeBoxNumber",
			"description": "The post office box number for PO box addresses.",
			"type": "string"
		},
		{
			"name": "postalCode",
			"description": "The postal code. For example, 94043.",
			"type": "string"
		},
		{
			"name": "streetAddress",
			"description": "The street address. For example, 1600 Amphitheatre Pkwy.",
			"type": "string"
    	}
	],
  "required": [
    "addressCountry",
    "streetAddress"
  ]
}
