=== tdwg/cd/standard/schemas/json/2.0/term-schemas/resource-relationship-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema#",
    "type": "object",
    "properties": {
        "$schema": {"type": "string"},
        "$id": {"type": "string"},
        "title": {"type": "string"},
        "description": {"type": "string"},
        "type": {"type": "string"},
        "properties": {"$ref": "#/$defs/properties_type"},
        "required": {"$ref": "#/$defs/required_type"}
    },
    "$defs": {
        "items_type": {
            "type": "object",
            "properties": {
                "$ref": {"type": "string"},
                "description": {"type": "string"},
                "type": {"type": "string"}
            }
        },
        "properties_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "description": {"type": "string"},
                    "type": {"type": "string"},
                    "items": {"$ref": "#/$defs/items_type"},
                    "minItems": {"type": "integer"},
                    "uniqueItems": {"type": "boolean"}
                },
                "required": [
                    "name",
                    "description",
                    "type"
                ]
            }
        },
        "required_type": {
            "type": "array",
            "minItems": 0,
            "items": {"type": "string"}
        }
    }
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/record-level.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/latimer-core-vocabulary.schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/record-level.json",
  "title": "Record Level",
  "description": "The machine-actionable information profile for the collection description digital object. Linked to the RDA PID Kernel recommendation (https://www.rd-alliance.org/system/files/RDA%20Recommendation%20on%20PID%20Kernel%20Information_final.pdf)",
  "type": "object",
  "properties": [
	{
			"name": "collectionDescriptionPID",
			"description": "An unambiguous reference to the collection description record.",
			"type": "string"
		},
		{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasObjectGroup",
			"description": "This property refers to one or more related instances of the ObjectGroup class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/object-group.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasPersonRole",
			"description": "This property refers to one or more related instances of the PersonRole class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/person-role.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasResourceRelationship",
			"description": "This property refers to one or more related instances of the ResourceRelationship class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/resource-relationship.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "isDerivedCollection",
			"description": "A flag to indicate that the collection description has been generated by aggregating data from one or more underlying datasets of its individual objects.",
			"type": "boolean"
		},
		{
			"name": "license",
			"description": "A legal document giving official permission to do something with the resource.",
			"type": "string"
		},
		{
			"name": "recordRights",
			"description": "Information about rights held in and over the resource.",
			"type": "string"
		},
		{
			"name": "rightsHolder",
			"description": "A person or organization owning or managing rights over the resource.",
			"type": "string"
    }
	],
  "required": [
    "collectionDescriptionPID",
    "license"
  ]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/object-classification.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/latimer-core-schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/object-classification.json",
  "title": "Object Classification",
  "description": "An informal classification of the type of objects within the ObjectGroup, using a hierarchical structure. This class is used to categorise the ObjectGroup according to an informal, self-referential hierarchy. For example, this can be used to create a hierarchy encompassing biological, geological and anthropological collections, where a single formal taxonomy isn't appropriate.",
  "type": "object",
  "properties": [
	{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasMeasurementOrFact",
			"description": "This property refers to one or more related instances of the MeasurementOrFact class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/measurement-or-fact.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasObjectClassification",
			"description": "This property refers to one or more related instances of the ObjectClassification class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/object-classification.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "objectClassificationLevel",
			"description": "The level of the ObjectClassification in the hierarchy.",
			"type": "string"
		},
		{
			"name": "objectClassificationName",
			"description": "A short title describing this ObjectClassification as a class, unit or grouping.",
			"type": "string"
    }
	],
  "required": [
    "objectClassificationName"
  ]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/contact-detail.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/latimer-core-schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/contact-detail.json",
  "title": "Contact Detail",
  "description": "Details of a method by which an entity such as a Person or OrganisationalUnit may be contacted. The Address class should be used to store physical or postal addresses. For all other types of contact details, this class should be used.",
  "type": "object",
  "properties": [
	{
			"name": "contactDetailCategory",
			"description": "The method of contact to which the contact detail applies.",
			"type": "string"
		},
		{
			"name": "contactDetailType",
			"description": "The type of contact detail, which can be used to distinguish between multiple contact details of the same contactDetailCategory.",
			"type": "string"
		},
		{
			"name": "contactDetailValue",
			"description": "The value of the contact detail, such as the phone number or email address.",
			"type": "string"
		},
		{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
    }
	],
  "required": [
    "contactDetailCategory",
    "contactDetailValue"
  ]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/storage-location.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/latimer-core-schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/storage-location.json",
  "title": "Storage Location",
  "description": "A physical location (such as a building, room, cabinet or drawer) within the holding institution where objects associated with the collection description are stored or exhibited.",
  "type": "object",
  "properties": [
	{
			"name": "hasAddress",
			"description": "This property refers to one or more related instances of the Address class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/address.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasMeasurementOrFact",
			"description": "This property refers to one or more related instances of the MeasurementOrFact class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/measurement-or-fact.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "locationDescription",
			"description": "Short textual description of the storage location of the group of items",
			"type": "string"
		},
		{
			"name": "locationName",
			"description": "A label used to identify a place where the collection is stored.",
			"type": "string"
		},
		{
			"name": "locationType",
			"description": "The nature of the location where the collection is stored.",
			"type": "string"
    }
	],
  "required": [
    "locationName"
  ]
}

=== tdwg/cd/standard/schemas/vocabulary/2.0/scheme-measurement-or-fact.json
{
  "$schema": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/json/2.0/latimer-core-schema.json",
  "$id": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/scheme-measurement-or-fact.json",
  "title": "Scheme Measurement Or Fact",
  "description": "A type of measurement or fact used by the CollectionDescriptionScheme, and the rules relating to its application. This class can be used to specify the qualitative and quantitative metrics that will be included in the CollectionDescriptionScheme using the MeasurementOrFact class, and dictate whether each will be mandatory and/or repeatable. This information can be used by software and queries to constrain and validate the Latimer Core dataset, and determine how and whether metrics can be aggregated and reported. The schemeMeasurementType property should correspond to the measurementType property of the MeasurementOrFact class in order to make the relevant association between the scheme definition and the stored data.",
  "type": "object",
  "properties": [
	{
			"name": "hasIdentifier",
			"description": "This property refers to one or more related instances of the Identifier class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/identifier.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "hasReference",
			"description": "This property refers to one or more related instances of the Reference class.",
			"type": "array",
			"items": {
		  "$ref": "https://raw.githubusercontent.com/tdwg/cd/review/json-schemas-dev/standard/schemas/vocabulary/2.0/reference.json"
		},
			"minItems": 0,
			"uniqueItems": true
		},
		{
			"name": "isMandatoryMetric",
			"description": "A flag to designate whether it is mandatory or optional for every collection description within the CollectionDescriptionScheme to include the measurement or fact defined by the schemeMeasurementType property.",
			"type": "boolean"
		},
		{
			"name": "isRepeatableMetric",
			"description": "A flag to designate whether multiple instances of the same schemeMeasurementType may be attached to a single entity.",
			"type": "boolean"
		},
		{
			"name": "schemeMeasurementType",
			"description": "A category of quantitative metric or qualitative fact that can be included in the CollectionDescriptionScheme.",
			"type": "string"
    }
	],
  "required": [
    "isMandatoryMetric",
    "isRepeatableMetric",
    "schemeMeasurementType"
  ]
}
